{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sayHi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSayBye"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name to say Hi to"}]}]},{"name":"shouldSayBye","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Wether to say bye or not"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/doccframework\/dummyclass\/sayhi(name:shouldsaybye:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/doccframework\/dummyclass\/sayhi(name:shouldsaybye:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass\/sayHi(name:shouldSayBye:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Use this method when you want to say hi to a name in the debug log"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sayHi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSayBye"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"sayHi(name:shouldSayBye:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DoccFramework@objc(cs)DummyClass(im)sayHiWithName:shouldSayBye:","modules":[{"name":"DoccFramework"}],"navigatorTitle":[{"kind":"identifier","text":"sayHiWithName:shouldSayBye:"}]},"hierarchy":{"paths":[["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework","doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass"]]},"references":{"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyClass":{"role":"symbol","title":"DummyClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DummyClass"}],"abstract":[{"type":"text","text":"This is just a dummy class called "},{"type":"codeVoice","code":"DummyClass"}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DummyClass"}],"url":"\/documentation\/doccframework\/dummyclass"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework":{"role":"collection","title":"DoccFramework","abstract":[{"type":"text","text":"The DoccFramework is a dummy framework, design to test the automatic generation of the framework on Github to produce a github pages page."}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework","kind":"symbol","type":"topic","url":"\/documentation\/doccframework"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyClass/sayHi(name:shouldSayBye:)":{"role":"symbol","title":"sayHi(name:shouldSayBye:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sayHi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSayBye"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use this method when you want to say hi to a name in the debug log"}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass\/sayHi(name:shouldSayBye:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sayHiWithName:shouldSayBye:"}],"url":"\/documentation\/doccframework\/dummyclass\/sayhi(name:shouldsaybye:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sayHiWithName:shouldSayBye:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sayHiWithName:shouldSayBye:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sayHiWithName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldSayBye:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"shouldSayBye"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyClass\/title","value":"DummyClass"},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyClass\/fragments","value":[{"kind":"identifier","text":"DummyClass"}]},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyClass~1sayHi(name:shouldSayBye:)\/title","value":"sayHiWithName:shouldSayBye:"},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyClass~1sayHi(name:shouldSayBye:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sayHiWithName:shouldSayBye:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}