{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DummyClass"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/doccframework\/dummyclass"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/doccframework\/dummyclass"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/se.apptrix.DoccFramework\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/se.apptrix.DoccFramework\/objc(pl)NSObject","doc:\/\/se.apptrix.DoccFramework\/s7CVarArgP","doc:\/\/se.apptrix.DoccFramework\/s28CustomDebugStringConvertibleP","doc:\/\/se.apptrix.DoccFramework\/s23CustomStringConvertibleP","doc:\/\/se.apptrix.DoccFramework\/SQ","doc:\/\/se.apptrix.DoccFramework\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is just a dummy class called "},{"type":"codeVoice","code":"DummyClass"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DummyClass"}],"title":"DummyClass","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DoccFramework@objc(cs)DummyClass","modules":[{"name":"DoccFramework"}],"navigatorTitle":[{"kind":"identifier","text":"DummyClass"}]},"hierarchy":{"paths":[["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass\/versionNumber"]},{"title":"Instance Methods","identifiers":["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass\/nonObjcMethod()","doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass\/sayHi(name:shouldSayBye:)"]}],"references":{"doc://se.apptrix.DoccFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/se.apptrix.DoccFramework\/SQ"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyClass/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/doccframework\/dummyclass\/init"},"doc://se.apptrix.DoccFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/se.apptrix.DoccFramework\/SH"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyClass/versionNumber":{"role":"symbol","title":"versionNumber","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The version number we have in this file"}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass\/versionNumber","kind":"symbol","type":"topic","url":"\/documentation\/doccframework\/dummyclass\/versionnumber"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyClass":{"role":"symbol","title":"DummyClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DummyClass"}],"abstract":[{"type":"text","text":"This is just a dummy class called "},{"type":"codeVoice","code":"DummyClass"}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DummyClass"}],"url":"\/documentation\/doccframework\/dummyclass"},"doc://se.apptrix.DoccFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/se.apptrix.DoccFramework\/s7CVarArgP"},"doc://se.apptrix.DoccFramework/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/se.apptrix.DoccFramework\/objc(cs)NSObject"},"doc://se.apptrix.DoccFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/se.apptrix.DoccFramework\/s28CustomDebugStringConvertibleP"},"doc://se.apptrix.DoccFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/se.apptrix.DoccFramework\/s23CustomStringConvertibleP"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework":{"role":"collection","title":"DoccFramework","abstract":[{"type":"text","text":"The DoccFramework is a dummy framework, design to test the automatic generation of the framework on Github to produce a github pages page."}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework","kind":"symbol","type":"topic","url":"\/documentation\/doccframework"},"doc://se.apptrix.DoccFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/se.apptrix.DoccFramework\/objc(pl)NSObject"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyClass/nonObjcMethod()":{"role":"symbol","title":"nonObjcMethod()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonObjcMethod"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method is not exposed to objc. It will just post to the log that it is called"}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass\/nonObjcMethod()","kind":"symbol","type":"topic","url":"\/documentation\/doccframework\/dummyclass\/nonobjcmethod()"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyClass/sayHi(name:shouldSayBye:)":{"role":"symbol","title":"sayHi(name:shouldSayBye:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sayHi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSayBye"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Use this method when you want to say hi to a name in the debug log"}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass\/sayHi(name:shouldSayBye:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sayHiWithName:shouldSayBye:"}],"url":"\/documentation\/doccframework\/dummyclass\/sayhi(name:shouldsaybye:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DummyClass"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DummyClass"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DummyClass"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass\/init","doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass\/sayHi(name:shouldSayBye:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/se.apptrix.DoccFramework\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DummyClass"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyClass\/title","value":"DummyClass"},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyClass\/fragments","value":[{"kind":"identifier","text":"DummyClass"}]},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyClass~1sayHi(name:shouldSayBye:)\/title","value":"sayHiWithName:shouldSayBye:"},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyClass~1sayHi(name:shouldSayBye:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sayHiWithName:shouldSayBye:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}