{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DummyObjcClass"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/doccframework\/dummyobjcclass"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/doccframework\/dummyobjcclass"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/se.apptrix.DoccFramework\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/se.apptrix.DoccFramework\/objc(pl)NSObject","doc:\/\/se.apptrix.DoccFramework\/s7CVarArgP","doc:\/\/se.apptrix.DoccFramework\/s28CustomDebugStringConvertibleP","doc:\/\/se.apptrix.DoccFramework\/s23CustomStringConvertibleP","doc:\/\/se.apptrix.DoccFramework\/SQ","doc:\/\/se.apptrix.DoccFramework\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyObjcClass","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is a simple dummy class"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DummyObjcClass"}],"title":"DummyObjcClass","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)DummyObjcClass","modules":[{"name":"DoccFramework"}],"navigatorTitle":[{"kind":"identifier","text":"DummyObjcClass"}]},"hierarchy":{"paths":[["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyObjcClass\/cheerHi()"]}],"references":{"doc://se.apptrix.DoccFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/se.apptrix.DoccFramework\/s23CustomStringConvertibleP"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyObjcClass":{"role":"symbol","title":"DummyObjcClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DummyObjcClass"}],"abstract":[{"type":"text","text":"This is a simple dummy class"}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyObjcClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DummyObjcClass"}],"url":"\/documentation\/doccframework\/dummyobjcclass"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework":{"role":"collection","title":"DoccFramework","abstract":[{"type":"text","text":"The DoccFramework is a dummy framework, design to test the automatic generation of the framework on Github to produce a github pages page."}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework","kind":"symbol","type":"topic","url":"\/documentation\/doccframework"},"doc://se.apptrix.DoccFramework/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/se.apptrix.DoccFramework\/objc(cs)NSObject"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyObjcClass/cheerHi()":{"role":"symbol","title":"cheerHi()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cheerHi"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Calling this function will cheer in the log using NSLog"}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyObjcClass\/cheerHi()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cheerHi"}],"url":"\/documentation\/doccframework\/dummyobjcclass\/cheerhi()"},"doc://se.apptrix.DoccFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/se.apptrix.DoccFramework\/SQ"},"doc://se.apptrix.DoccFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/se.apptrix.DoccFramework\/objc(pl)NSObject"},"doc://se.apptrix.DoccFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/se.apptrix.DoccFramework\/s28CustomDebugStringConvertibleP"},"doc://se.apptrix.DoccFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/se.apptrix.DoccFramework\/s7CVarArgP"},"doc://se.apptrix.DoccFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/se.apptrix.DoccFramework\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DummyObjcClass"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DummyObjcClass"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DummyObjcClass"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyObjcClass\/cheerHi()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/se.apptrix.DoccFramework\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DummyObjcClass"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyObjcClass\/title","value":"DummyObjcClass"},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyObjcClass\/fragments","value":[{"kind":"identifier","text":"DummyObjcClass"}]},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyObjcClass~1cheerHi()\/title","value":"cheerHi"},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyObjcClass~1cheerHi()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cheerHi"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}