{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cheerHi"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/doccframework\/dummyobjcclass\/cheerhi()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/doccframework\/dummyobjcclass\/cheerhi()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyObjcClass\/cheerHi()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Calling this function will cheer in the log using NSLog"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cheerHi"},{"kind":"text","text":"()"}],"title":"cheerHi()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)DummyObjcClass(im)cheerHi","modules":[{"name":"DoccFramework"}],"navigatorTitle":[{"kind":"identifier","text":"cheerHi"}]},"hierarchy":{"paths":[["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework","doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyObjcClass"]]},"references":{"doc://se.apptrix.DoccFramework/documentation/DoccFramework":{"role":"collection","title":"DoccFramework","abstract":[{"type":"text","text":"The DoccFramework is a dummy framework, design to test the automatic generation of the framework on Github to produce a github pages page."}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework","kind":"symbol","type":"topic","url":"\/documentation\/doccframework"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyObjcClass/cheerHi()":{"role":"symbol","title":"cheerHi()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cheerHi"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Calling this function will cheer in the log using NSLog"}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyObjcClass\/cheerHi()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cheerHi"}],"url":"\/documentation\/doccframework\/dummyobjcclass\/cheerhi()"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyObjcClass":{"role":"symbol","title":"DummyObjcClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DummyObjcClass"}],"abstract":[{"type":"text","text":"This is a simple dummy class"}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyObjcClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DummyObjcClass"}],"url":"\/documentation\/doccframework\/dummyobjcclass"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cheerHi"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cheerHi"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"cheerHi"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyObjcClass~1cheerHi()\/title","value":"cheerHi"},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyObjcClass~1cheerHi()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cheerHi"}]},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyObjcClass\/title","value":"DummyObjcClass"},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyObjcClass\/fragments","value":[{"kind":"identifier","text":"DummyObjcClass"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}