name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Set Xcode version to 14.0
        run: sudo xcode-select -s "/Applications/Xcode_14.0.app"
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          
      - name: Update local branch
        run: |
          git fetch origin main		
          git reset --hard origin/main
        
      - name: Build documentation
        env:
          scheme: ${{ 'default' }}
        run: |
          xcodebuild docbuild -scheme DoccFramework -destination 'generic/platform=ios' -derivedDataPath '.documentationArchive/'
          
      - name: Create web folder
        run: |
          $(xcrun --find docc) process-archive transform-for-static-hosting .documentationArchive/Build/Products/Debug-iphoneos/DoccFramework.doccarchive --output-path '.documentation' --hosting-base-path 'DoccFramework'
          
      - name: Commit changes
        run: |
          git add .documentation
          git commit -m "Updated the documentation"
          
      - name: Push changes
        run: |
          git push --force
