{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can have a look at the framework at "},{"type":"reference","isActive":true,"identifier":"https:\/\/www.github.com\/ppeelen\/DoccFramework"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/doccframework"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/doccframework"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The DoccFramework is a dummy framework, design to test the automatic generation of the framework on Github to produce a github pages page."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"DoccFramework","title":"DoccFramework","symbolKind":"module","role":"collection","modules":[{"name":"DoccFramework"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Articles","identifiers":["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/GettingStarted"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass","doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyObjcClass"]}],"references":{"doc://se.apptrix.DoccFramework/documentation/DoccFramework":{"role":"collection","title":"DoccFramework","abstract":[{"type":"text","text":"The DoccFramework is a dummy framework, design to test the automatic generation of the framework on Github to produce a github pages page."}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework","kind":"symbol","type":"topic","url":"\/documentation\/doccframework"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyObjcClass":{"role":"symbol","title":"DummyObjcClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DummyObjcClass"}],"abstract":[{"type":"text","text":"This is a simple dummy class"}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyObjcClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DummyObjcClass"}],"url":"\/documentation\/doccframework\/dummyobjcclass"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DoccFrameworkVersionString":{"role":"symbol","title":"DoccFrameworkVersionString","fragments":[{"kind":"identifier","text":"DoccFrameworkVersionString"}],"abstract":[{"type":"text","text":"Project version string for DoccFramework."}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DoccFrameworkVersionString","kind":"symbol","type":"topic","url":"\/documentation\/doccframework\/doccframeworkversionstring"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DoccFrameworkVersionNumber":{"role":"symbol","title":"DoccFrameworkVersionNumber","fragments":[{"kind":"identifier","text":"DoccFrameworkVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for DoccFramework."}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DoccFrameworkVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/doccframework\/doccframeworkversionnumber"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/DummyClass":{"role":"symbol","title":"DummyClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DummyClass"}],"abstract":[{"type":"text","text":"This is just a dummy class called "},{"type":"codeVoice","code":"DummyClass"}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DummyClass"}],"url":"\/documentation\/doccframework\/dummyclass"},"doc://se.apptrix.DoccFramework/documentation/DoccFramework/GettingStarted":{"role":"article","title":"Getting Started","abstract":[{"type":"text","text":"The DoccFramework is generated using Apple’s DocC Documentation."}],"identifier":"doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/GettingStarted","kind":"article","type":"topic","url":"\/documentation\/doccframework\/gettingstarted"},"https://www.github.com/ppeelen/DoccFramework":{"title":"https:\/\/www.github.com\/ppeelen\/DoccFramework","titleInlineContent":[{"type":"text","text":"https:\/\/www.github.com\/ppeelen\/DoccFramework"}],"type":"link","identifier":"https:\/\/www.github.com\/ppeelen\/DoccFramework","url":"https:\/\/www.github.com\/ppeelen\/DoccFramework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/GettingStarted"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyClass","doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DummyObjcClass"]},{"title":"Variables","identifiers":["doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DoccFrameworkVersionNumber","doc:\/\/se.apptrix.DoccFramework\/documentation\/DoccFramework\/DoccFrameworkVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyObjcClass\/title","value":"DummyObjcClass"},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyObjcClass\/fragments","value":[{"kind":"identifier","text":"DummyObjcClass"}]},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyClass\/title","value":"DummyClass"},{"op":"replace","path":"\/references\/doc:~1~1se.apptrix.DoccFramework~1documentation~1DoccFramework~1DummyClass\/fragments","value":[{"kind":"identifier","text":"DummyClass"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}